### ISSUE TITLE
How are files handled after snapshot?

### ISSUE THREAD

**Issue by thedewpoint** [loehnertz/Tanglestash#1]
I think your module is great. I have had the same idea before but determined that it was useless because after snapshots are created, all history (and arbitrary data) are removed except for where units of IOTA are stored. This is why after snapshots you have to reattach a bunch of times to determine what your last used public address was from your seed. How does your code handle this situation?

edit source: https://forum.helloiota.com/4659/How-do-I-prepare-for-a-snapshot

**Comment by loehnertz** [comment]
Hi there! You found this repo really fast, I just released it a couple of hours ago 😄 
How did you found it? 😊

You are totally right, snapshots will cause persisted data to 'disappear'.
At the moment I don't have a solution for that; one could use a Permanode in the future (so far they are not implemented). You might have already knew this, in case not search the roadmap for 'permanode' (https://blog.iota.org/iota-development-roadmap-74741f37ed01).

But generally I gotta say that this module is more of a proof-of-concept rather than a finished solution. I will definitely continue developing it though, as I already have a couple of ideas for improvement.

**Comment by thedewpoint** [comment]
That's pretty funny. I was looking for an iota seed generator module on npmjs so I just typed in "iota" and then I saw this module and decided to research it. I love the concept.

**Comment by loehnertz** [comment]
Thanks for the feedback! Two btw's left:
1) In case you are on macOS oder Linux you can do so on your local machine without a module: https://iotasupport.com/gui-newseed.shtml
Matter of fact, you could even use my module with its method [`generateRandomIotaSeed()`](https://github.com/loehnertz/Tanglestash#generaterandomiotaseed) 😄 
2) My favorite TV series of all time is The Office 😊

**Comment by thedewpoint** [comment]
Thank you! I have seen this, it's how I generate my own seeds. But I was
looking for a module to use for a module that i'm writing as well, so I
wanted it to be dynamic and callable from my JS code. I ended up using
 "iota-seed-generator": "^1.0.0".

Also the office is my absolute favorite show as well. Let me know if you
have any additional work you could use help with on your project. I'm still
learning the IOTA api but I'm very experienced with JS, and I think your
project idea would be an awesome use case for the network.

**Comment by loehnertz** [comment]
Alright, thanks for the offer! :)
I will let you know when I could need some help.
